version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  target-branch: master
  reviewers:
  - martinfrancois
  assignees:
  - martinfrancois
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a, < 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.53
    - 10.17.54
    - 10.17.55
    - 10.17.56
    - 10.17.57
    - 10.17.58
    - 15.0.0
  - dependency-name: webdriverio
    versions:
    - 6.12.1
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.5
    - 7.5.0
    - 7.5.1
  - dependency-name: "@wdio/sync"
    versions:
    - 6.11.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.5
    - 7.5.0
    - 7.5.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@wdio/logger"
    versions:
    - 6.10.10
    - 7.0.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  target-branch: v5
  reviewers:
  - martinfrancois
  assignees:
  - martinfrancois
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a, < 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@wdio/logger"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@wdio/sync"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: webdriverio
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.53
    - 10.17.54
    - 10.17.55
    - 10.17.56
    - 10.17.57
    - 10.17.58
    - 15.0.0
  - dependency-name: webdriverio
    versions:
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.5
    - 7.5.0
    - 7.5.1
  - dependency-name: "@wdio/sync"
    versions:
    - 5.23.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.5
    - 7.5.0
    - 7.5.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 3.9.8
    - 4.0.2
  - dependency-name: "@wdio/logger"
    versions:
    - 7.0.0
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
